Imprting numpy and pandas

In [1]:
import numpy as np
import pandas as pd

Reading the data set

In [2]:
df=pd.read_csv("C:/Users/Sanat/OneDrive/Desktop/New folder/week-3/stress.csv")
df

subreddit post_id sentence_range  \
0                 ptsd  8601tu       (15, 20)   
1           assistance  8lbrx9         (0, 5)   
2                 ptsd  9ch1zh       (15, 20)   
3        relationships  7rorpp        [5, 10]   
4     survivorsofabuse  9p2gbc         [0, 5]   
...                ...     ...            ...   
2833     relationships  7oee1t       [35, 40]   
2834              ptsd  9p4ung       [20, 25]   
2835           anxiety  9nam6l        (5, 10)   
2836    almosthomeless  5y53ya        [5, 10]   
2837              ptsd  5y25cl         [0, 5]   

                                                   text     id  label  \
0     He said he had not felt that way before, sugge...  33181      1   
1     Hey there r/assistance, Not sure if this is th...   2606      0   
2     My mom then hit me with the newspaper and it s...  38816      1   
3     until i met my new boyfriend, he is amazing, h...    239      1   
4     October is Domestic Violence Awareness Month a...   1421      1   
...                                                 ...    ...    ...   
2833  * Her, a week ago: Precious, how are you? (I i...   1713      0   
2834  I don't have the ability to cope with it anymo...   1133      1   
2835  In case this is the first time you're reading ...  10442      0   
2836  Do you find this normal? They have a good rela...   1834      0   
2837  I was talking to my mom this morning and she s...    961      1   

      confidence  social_timestamp  social_karma  syntax_ari  ...  \
0       0.800000        1521614353             5    1.806818  ...   
1       1.000000        1527009817             4    9.429737  ...   
2       0.800000        1535935605             2    7.769821  ...   
3       0.600000        1516429555             0    2.667798  ...   
4       0.800000        1539809005            24    7.554238  ...   
...          ...               ...           ...         ...  ...   
2833    1.000000        1515187044            13   -1.369333  ...   
2834    1.000000        1539827412            33    9.425478  ...   
2835    1.000000        1539269312             2   11.060675  ...   
2836    0.571429        1488938143             4    2.421912  ...   
2837    0.571429        1488909516             2    0.835254  ...   

      lex_dal_min_pleasantness  lex_dal_min_activation  lex_dal_min_imagery  \
0                       1.0000                  1.1250                  1.0   
1                       1.1250                  1.0000                  1.0   
2                       1.0000                  1.1429                  1.0   
3                       1.0000                  1.1250                  1.0   
4                       1.0000                  1.1250                  1.0   
...                        ...                     ...                  ...   
2833                    1.4000                  1.0000                  1.0   
2834                    1.0000                  1.0000                  1.0   
2835                    1.1250                  1.1250                  1.0   
2836                    1.1111                  1.1429                  1.0   
2837                    1.0000                  1.0000                  1.0   

      lex_dal_avg_activation  lex_dal_avg_imagery  lex_dal_avg_pleasantness  \
0                    1.77000              1.52211                   1.89556   
1                    1.69586              1.62045                   1.88919   
2                    1.83088              1.58108                   1.85828   
3                    1.75356              1.52114                   1.98848   
4                    1.77644              1.64872                   1.81456   
...                      ...                  ...                       ...   
2833                 1.71133              1.45301                   2.00304   
2834                 1.65003              1.56842                   1.81527   
2835                 1.79768              1.49074         

Cheching for null values

In [3]:
df.isnull().sum()

subreddit                   0
post_id                     0
sentence_range              0
text                        0
id                          0
                           ..
lex_dal_avg_pleasantness    0
social_upvote_ratio         0
social_num_comments         0
syntax_fk_grade             0
sentiment                   0
Length: 116, dtype: int64

cleaning the data by removing unwanted data from the dataset

In [4]:
import nltk
import re
import string
from nltk. corpus import stopwords
nltk.download('stopwords')
stemmer=nltk.SnowballStemmer("english")
stopword=set(stopwords.words('english'))
def clean(text):
    text=str(text).lower()
    text=re.sub('\n',' ',text)
    text=re.sub('[%s]'% re.escape(string.punctuation),' ',text)
    text=re.sub('\[.*?\]',' ',text)
    text=re.sub('https?://\S+/www\. \S+',' ',text)
    text=re.sub('<. *?>+',' ',text)
    text=re.sub('\w*\d\w*',' ',text)
    text=[word for word in text. split(' ') if word not in stopword]
    text=" ".join(text)
    text=[stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text
df["text"]=df["text"].apply(clean)
    

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sanat\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


importing countvectorizer and converting the textual format to the numeric format

In [5]:
from sklearn. feature_extraction. text import CountVectorizer
cv=CountVectorizer()
x=df["text"].values
y=df['label'].values
x=cv.fit_transform(x)
v=x.toarray()
print(v)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
df.shape

(2838, 116)

Spliting the data set for the training and tesing the model

In [7]:
xtrain=x[:1501]
ytrain=y[:1501]
xtest=x[1501:]
ytest=y[1501:]


importing the bernoulliNB algorithum

In [8]:

from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB(binarize=0.0)
model=bnb.fit(xtrain,ytrain)

testing the data by mannual input

In [9]:
user=input("Enter how your feeling")
data=cv.transform([user]).toarray()
output=model.predict(data)
print(output)

[1]


checking the model score

In [10]:
print(bnb.score(xtrain,ytrain)*100)

92.53830779480346
